[package]
name = "farming_game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rstest = "0.18.2"

# Added Ratatui and Crossterm
ratatui = { version = "0.26.1", features = ["crossterm"] }
crossterm = "0.27.0"